<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Google</name>
   <tag></tag>
   <elementGuidId>089995cc-a63c-4e50-8512-0ce4c9c2da92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='googleLogin2182']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#googleLogin2182</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3efc244e-6d55-4b88-b5c2-a1b2e7e7dff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>a1cd3abe-1253-4c06-b8a3-c2679b7afbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>googleLogin2182</value>
      <webElementGuid>709f10b6-5297-4646-8fac-6488bbcf39d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>google-login</value>
      <webElementGuid>52f77466-32ff-4d3f-91fa-2c257b14bfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-c4oqdn-unf-btn eg8apji0</value>
      <webElementGuid>ecc4635a-d255-4b6a-959b-a2abae7837b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>027ffd8c-6a7b-4ff6-9012-c00d1ad86b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;googleLogin2182&quot;)</value>
      <webElementGuid>f76dd024-227d-4928-9a2b-ebdfdd2d51d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='googleLogin2182']</value>
      <webElementGuid>0b2a4214-f48e-4852-9493-6687145cd6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Akun Untuk Masuk'])[1]/following::button[1]</value>
      <webElementGuid>845adf85-7018-43f3-bfcb-512fc270cf50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'googleLogin2182', '&quot;', ')')])[1]/following::button[2]</value>
      <webElementGuid>3819300a-72b7-4769-90fd-87cfd2784dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/div/button</value>
      <webElementGuid>8c04b860-2997-4f1c-b00c-0b02b054816e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'googleLogin2182' and (text() = 'Google' or . = 'Google')]</value>
      <webElementGuid>bef2d953-da62-45af-998d-2853fe6c3047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
