<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b0e3fdc6-c2dd-4c8e-917f-ac31d699f979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdpVariantContainer']/div/div[2]/button/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Putih Abu&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>06693898-abb6-437d-b553-3eb3ab027e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>48154d32-4b71-46bd-9a9a-f7a61e9a7801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ecs7.tokopedia.net/img/cache/100-square/VqbcmM/2021/8/31/073de62a-6fe3-4244-9341-0465106753fe.jpg</value>
      <webElementGuid>5d18adf7-39e8-4d98-8105-2a0fbe99fc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Putih Abu</value>
      <webElementGuid>fe6e6647-7863-4c15-b99d-b689db5c63e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Putih Abu</value>
      <webElementGuid>609a7148-d948-4e76-9aad-1203b9752a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdpVariantContainer&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-12ymujy&quot;]/button[@class=&quot;css-tvxvfx&quot;]/div[1]/img[1]</value>
      <webElementGuid>08bf5ec1-8672-4f72-812c-8fbd3e5cea07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpVariantContainer']/div/div[2]/button/div/img</value>
      <webElementGuid>85532ce3-bb7b-480e-b712-9c0b4e930ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Putih Abu']</value>
      <webElementGuid>83c94507-c9c7-408c-a9f9-3597e0b3fc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/img</value>
      <webElementGuid>de4b6820-d8a7-4b89-ab01-7fe9b4b47c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ecs7.tokopedia.net/img/cache/100-square/VqbcmM/2021/8/31/073de62a-6fe3-4244-9341-0465106753fe.jpg' and @title = 'Putih Abu' and @alt = 'Putih Abu']</value>
      <webElementGuid>f5746b6e-df25-4ee5-bd52-e8bccb7143bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
