<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>36df02f6-5466-4ae3-9922-68d445ec95fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='be-navigation-mobile']/div[3]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5fb25e37-c3f2-46c7-8c9d-9be2099653c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://gitlab.com/users/sign_up/</value>
      <webElementGuid>95f6935e-ec8b-42a9-990e-0c2bfec4596a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>32603e59-1ad7-43f4-8388-25f745f2cf8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slp-btn nav-menu_icon slp-btn-ghost</value>
      <webElementGuid>cab69ebf-8033-4b20-a742-452363e56129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Register </value>
      <webElementGuid>545e3e58-4f73-43a0-9ebf-97ec8d6958c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be-navigation-mobile&quot;)/div[@class=&quot;nav-menu&quot;]/div[1]/ul[1]/li[2]/a[@class=&quot;slp-btn nav-menu_icon slp-btn-ghost&quot;]</value>
      <webElementGuid>d64acc1d-9d48-411f-bf4c-05427e6c19ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='be-navigation-mobile']/div[3]/div/ul/li[2]/a</value>
      <webElementGuid>8ed390c3-552b-4f81-ab58-40d3ebb1b7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Register')])[2]</value>
      <webElementGuid>ece421ec-b835-485c-9a45-b6c9219deee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::a[1]</value>
      <webElementGuid>b632245f-16a5-47ce-825d-1586dc378b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[2]/following::a[2]</value>
      <webElementGuid>c8008084-4d3c-452f-8c8d-4a465064f32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>d7b2852d-fa16-412d-a627-9ddd82a7758c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Talk to an expert'])[3]/preceding::a[1]</value>
      <webElementGuid>c4dfd9b0-3ca5-4586-9c1c-9ee7fe120712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://gitlab.com/users/sign_up/')])[3]</value>
      <webElementGuid>df5cade3-5940-4e56-bb34-12889e85710c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[2]/a</value>
      <webElementGuid>0e6f99eb-d5f2-420e-b440-a7b9302b0c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://gitlab.com/users/sign_up/' and (text() = ' Register ' or . = ' Register ')]</value>
      <webElementGuid>81f0ea8b-6e4c-43e8-8e47-fab4dc7a313c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
