<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bisa pilih alamat pengirimanmu dulu_unf_c11ad3</name>
   <tag></tag>
   <elementGuidId>36522d40-9845-4e1c-9d2c-a3e7ba7cfc3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.unf-coachmark__next-button.css-64apm5.e1o9jid35</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6faae8d-a9e9-469f-8a4b-2398a7b0dbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unf-coachmark__next-button css-64apm5 e1o9jid35</value>
      <webElementGuid>fcbdbe4e-7a9d-4055-8e82-eef1a7a405bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[6]/div[@class=&quot;css-j1l6ki-unf-coachmark e1o9jid31&quot;]/section[@class=&quot;css-1frsvni-unf-card eeeacht0&quot;]/div[@class=&quot;unf-coachmark__content-wrapper css-8atqhb e1o9jid32&quot;]/div[@class=&quot;unf-coachmark__footer css-1i5hdkt e1o9jid34&quot;]/div[@class=&quot;unf-coachmark__action-wrapper css-1xhj18k e1o9jid33&quot;]/div[@class=&quot;unf-coachmark__next-button css-64apm5 e1o9jid35&quot;]</value>
      <webElementGuid>65043db6-7d13-444e-88f3-79d74cacc072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div</value>
      <webElementGuid>4eba9c36-7064-4616-ab4f-93451877930c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
