<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cek Sekarang_css-1c345mg</name>
   <tag></tag>
   <elementGuidId>df89626c-933a-443b-b734-a8797dcb55c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='757174298']/div/div/div/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.css-1c345mg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4ff1939-2188-4a7b-84e0-41ccfc5dd9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>imgProduct</value>
      <webElementGuid>dd551802-f1df-488e-b9a8-d9b22526179e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1c345mg</value>
      <webElementGuid>2ff09694-6cf9-499c-ba13-fc5eab7c7df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>f5380dbf-fbf5-41e4-9e51-ef1995ecccbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>a03943bd-f443-40c8-8509-f9e75353926b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.tokopedia.net/img/cache/200-square/VqbcmM/2022/4/11/abcf634e-969c-4b23-85a7-1b0312beda9b.jpg</value>
      <webElementGuid>8c29f250-e051-42f7-a9bf-e1a75c8f22ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>910 Nineten Geist Ekiden Sepatu Running - Hitam Biru - 42</value>
      <webElementGuid>78214dff-3457-4b43-81d0-b6d7073d0f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;757174298&quot;)/div[@class=&quot;css-5fmc3z&quot;]/div[@class=&quot;css-1w757ve&quot;]/div[@class=&quot;css-1c4umxf&quot;]/div[@class=&quot;pcv3__container css-gfx8z3&quot;]/div[@class=&quot;css-1f2quy8&quot;]/a[1]/div[@class=&quot;responsive css-1eg7f6s&quot;]/img[@class=&quot;css-1c345mg&quot;]</value>
      <webElementGuid>e9eceb72-61cb-4dd5-a2a2-f25791ab4fb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='757174298']/div/div/div/div/div/a/div/img</value>
      <webElementGuid>9de28829-119e-431f-ab25-22e9e8dae5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='910 Nineten Geist Ekiden Sepatu Running - Hitam Biru - 42']</value>
      <webElementGuid>9c5096d0-a6ca-43d9-834c-0dddfb8326c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>31f59f73-97a8-44d8-a698-7c0ddce09b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.tokopedia.net/img/cache/200-square/VqbcmM/2022/4/11/abcf634e-969c-4b23-85a7-1b0312beda9b.jpg' and @alt = '910 Nineten Geist Ekiden Sepatu Running - Hitam Biru - 42']</value>
      <webElementGuid>16611e23-7f15-45e6-b752-6aafefcd6512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
