<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjut</name>
   <tag></tag>
   <elementGuidId>df7f073d-1ce8-4bf0-8ef4-1ab22d6b0794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mb-64.bl-button.bl-button--primary.bl-button--medium.bl-button--block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55f94a6f-46ca-4ff7-a8af-a5e7dc706020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-64 bl-button bl-button--primary bl-button--medium bl-button--block</value>
      <webElementGuid>9918b13c-852e-4240-ab06-3db011910967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lanjut </value>
      <webElementGuid>e366b38f-7bef-48a2-8242-8de86ff3a29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;container&quot;]/div[@class=&quot;ph-24 bl-card has-elevation-1 bl-card--outlined&quot;]/section[@class=&quot;u-align-center pv-24&quot;]/button[@class=&quot;mb-64 bl-button bl-button--primary bl-button--medium bl-button--block&quot;]</value>
      <webElementGuid>dc48f5f4-a771-485f-95f6-1c2b18b12b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9cd9ed2f-94eb-41e8-b4d8-18febe9507ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Lanjut ' or . = ' Lanjut ')]</value>
      <webElementGuid>480f8e21-dafb-42b0-acb7-d7559a3a8cb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
