<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CXO Media_dtkframebar__icons dtkfram_856c15</name>
   <tag></tag>
   <elementGuidId>4e3968ae-b8f3-4d4e-aad7-fbb0547e5af9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='search_navbar']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.dtkframebar__icons.dtkframebar__icons-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac38d70d-f56c-448f-bb3c-0f4ef2437615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dtkframebar__icons dtkframebar__icons-search</value>
      <webElementGuid>5bd8f7c9-bea6-4a10-b30e-dbf0a3e6c103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_navbar&quot;)/button[@class=&quot;dtkframebar__icons dtkframebar__icons-search&quot;]</value>
      <webElementGuid>946777e7-2edb-4eb0-9aff-1cfc8f71c8fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_navbar']/button</value>
      <webElementGuid>ae9c8b47-a9fe-4533-9c81-6ebf97fca184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9ca71cf9-389e-4887-a593-39e93f89a83c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
